namespace Kaleido.Processor;

/// <summary>
/// Represents the outcome of a process step after execution
/// or evaluation by the process runtime.
/// </summary>
public enum StepExecutionOutcome
{
    /// <summary>
    /// The step has not yet been evaluated or executed.
    /// </summary>
    Pending,

    /// <summary>
    /// The step completed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// The step executed but did not complete successfully.
    /// </summary>
    Failed,

    /// <summary>
    /// The step could not be executed because one or more
    /// required prerequisites were not satisfied.
    /// </summary>
    Blocked,

    /// <summary>
    /// The step was intentionally stopped and will not continue.
    /// </summary>
    Canceled
}

/// <summary>
/// Represents the processing status of a specific step request
/// recorded in the processor execution history.
/// </summary>
public enum StepExecutionStatus
{
    /// <summary>
    /// The request has not yet been processed.
    /// </summary>
    Pending,

    /// <summary>
    /// The request was processed successfully.
    /// </summary>
    Completed,

    /// <summary>
    /// The request failed validation and was never executed.
    /// </summary>
    ValidationFailed,

    /// <summary>
    /// An unexpected exception occurred while processing the request.
    /// </summary>
    Exception,

    Skipped,
    Canceled
}

/// <summary>
/// Indicates the severity of a planning, validation,
/// or diagnostic message generated by the framework.
/// </summary>
public enum MessageType
{
    /// <summary>
    /// Informational message that does not affect planning
    /// or execution.
    /// </summary>
    Information,

    /// <summary>
    /// Warning message indicating a potential issue that
    /// does not prevent processing.
    /// </summary>
    Warning,

    /// <summary>
    /// Error message indicating a condition that prevents
    /// the candidate from being included in the execution plan.
    /// </summary>
    Error
}

/// <summary>
/// Represents the action the execution processor should take
/// after evaluating the outcome of a step execution.
/// </summary>
public enum ExecutionDecisionType
{
    /// <summary>
    /// Execution can continue immediately using the specified
    /// next candidate.
    /// </summary>
    Continue,

    /// <summary>
    /// The process has reached a terminal state and no further
    /// execution is possible or required.
    /// </summary>
    Complete,

    /// <summary>
    /// The step executed successfully, but the business outcome
    /// indicated failure and execution cannot continue.
    /// </summary>
    BusinessFailure,

    /// <summary>
    /// A process rule or framework invariant was violated.
    /// Examples include illegal graph transitions or invalid
    /// required step selections.
    /// </summary>
    ProcessViolation,

    /// <summary>
    /// The step executed successfully and is handing off to a
    /// different processor for continued execution.
    /// </summary>
    HandOff,

    /// <summary>
    /// Execution cannot continue until a specific next step
    /// is supplied by the consumer.
    /// </summary>
    AwaitingRequiredStep,

    /// <summary>
    /// Execution cannot continue because no executable candidate
    /// was supplied. The consumer must select one of the available
    /// next steps returned by the process.
    /// </summary>
    AwaitingStepSelection
}

public enum ProcessExecutionState
{
    Active,
    Complete,
    BusinessFailure,
    ProcessViolation,
    HandOff,
    AwaitingRequiredStep,
    AwaitingStepSelection,
    Exception,
    Canceled
}

/// <summary>
/// Represents the state of a step candidate during the planning phase.
/// </summary>
public enum StepCandidateStatus
{
    /// <summary>
    /// Initial state before any planning or validation has occurred.
    /// </summary>
    Pending,

    /// <summary>
    /// The candidate was successfully created from the request
    /// and is eligible for validation and consistency checks.
    /// </summary>
    Built,

    /// <summary>
    /// The candidate failed validation or consistency checks
    /// and cannot participate in the execution plan.
    /// </summary>
    Invalid,

    /// <summary>
    /// The step has already been completed for the processor
    /// and does not need to be included in the execution plan.
    /// </summary>
    Satisfied
}
