<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
    <Using Include="Kaleido.Processor" />
    <Using Include="Kaleido.Processor.Execution" />
  		<Using Include="Kaleido.Queryable.Query" />
</ItemGroup>

<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Kaleido\Kaleido.csproj" />
	  <ProjectReference Include="..\Data\Kaleido.Samples.ECommerce.Data.csproj" />
	</ItemGroup>

</Project>
