<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.TestHost" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Kaleido.Http\Kaleido.Http.csproj" />
		<ProjectReference Include="..\Kaleido.UnitTests\Kaleido.UnitTests.csproj" />
	</ItemGroup>
</Project>
