<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Deterministic>true</Deterministic>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RestoreLockedMode Condition="'$(CI)' != 'true'">false</RestoreLockedMode>
        <NuGetAudit>true</NuGetAudit>
    </PropertyGroup>
</Project>
