<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.AspNetCore.TestHost" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Kaleido.Http\Kaleido.Http.csproj" />
		<ProjectReference Include="..\..\src\Kaleido.Http.Client\Kaleido.Http.Client.csproj" />
		<ProjectReference Include="..\..\src\Kaleido.Http.Abstractions\Kaleido.Http.Abstractions.csproj" />
	</ItemGroup>
</Project>
