global using System.Diagnostics.CodeAnalysis;
global using Kaleido.Eventing;
global using Kaleido.Exceptions;
global using Kaleido.Observability;
global using Kaleido.Processor;
global using Kaleido.Processor.Execution;
global using Kaleido.Processor.Planning;
global using Kaleido.Queryable;
global using Kaleido.Queryable.Query;
