namespace Kaleido.Eventing;

/// <summary>
/// Correlation and traceability context attached to every queryable domain event.
/// Populated by the framework from the active <see cref="Kaleido.Observability.KaleidoCorrelationContext"/>
/// and <see cref="KaleidoServiceOptions"/> at event creation time.
/// </summary>
[ExcludeFromCodeCoverage]
public sealed record QueryableEventContext
{
    /// <summary>
    /// The unique identifier of the originating request.
    /// Always populated — generated by the framework if not supplied by the caller via <c>X-Kaleido-Request-Id</c>.
    /// Pass the same value on all service calls in a user action to correlate events across service boundaries.
    /// </summary>
    public required string RequestId { get; init; }

    /// <summary>The service that emitted this event, from <see cref="KaleidoServiceOptions.ServiceName"/>.</summary>
    public required string ServiceName { get; init; }

    /// <summary>
    /// The process instance associated with this query, if the caller had an active process
    /// and propagated <c>X-Kaleido-Process-Id</c>. Null for queries made outside a process context.
    /// </summary>
    public Guid? ProcessId { get; init; }

    /// <summary>
    /// The step that called this query (<c>X-Kaleido-Calling-Step</c>), in
    /// <see cref="CallingProcessorName"/>. <c>null</c> when not called from a processor step.
    /// </summary>
    public string? CallingStepName { get; init; }

    /// <summary>The query source that was executed (its type name).</summary>
    public required string QuerySourceName { get; init; }

    /// <summary>The query view that was executed, if applicable. Null for direct and delegated source queries.</summary>
    public string? QueryViewName { get; init; }

    /// <summary>
    /// The stable instance identifier of the service that produced this event.
    /// Always from <see cref="KaleidoServiceOptions.InstanceId"/> — never from an inbound header.
    /// </summary>
    public string? ProcessorInstanceId { get; init; }

    /// <summary>
    /// The processor whose step called this query (<c>X-Kaleido-Calling-Processor</c>).
    /// <c>null</c> when not called from a processor step.
    /// </summary>
    public string? CallingProcessorName { get; init; }
}
