namespace Kaleido.Observability;

/// <summary>
/// Correlation for the current request. <see cref="RequestId"/> and <see cref="ProcessId"/>
/// are end-to-end: forwarded unchanged on every hop. <see cref="CallingProcessorName"/> and
/// <see cref="CallingStepName"/> are per-hop: they describe the processor step that called
/// this service and are never forwarded. A service's own instance id is never on the wire.
/// </summary>
[ExcludeFromCodeCoverage]
public sealed record KaleidoCorrelationContext
{
    /// <summary>
    /// The unique identifier of the originating request.
    /// Always non-empty — generated by the transport layer if not supplied by the caller.
    /// </summary>
    public string RequestId
    {
        get;
        init;
    } = string.Empty;

    /// <summary>The process instance this request belongs to (end-to-end).</summary>
    public Guid? ProcessId
    {
        get;
        init;
    }

    /// <summary>
    /// The processor whose step made this call (per-hop, inbound). <c>null</c> when the
    /// call was not made from inside a processor step — e.g. routed or registry calls.
    /// </summary>
    public string? CallingProcessorName
    {
        get;
        init;
    }

    /// <summary>The step in <see cref="CallingProcessorName"/> that made this call (per-hop, inbound).</summary>
    public string? CallingStepName
    {
        get;
        init;
    }

    /// <summary>
    /// The step this service is currently executing. Set by the runtime for a step
    /// handler's scope; outbound calls made from that scope stamp it, with this
    /// service's name, as the calling processor and step. <c>null</c> outside a step.
    /// </summary>
    public string? ExecutingStepName
    {
        get;
        init;
    }

    /// <summary>
    /// Name of the authenticated caller, populated by the transport from the
    /// request principal — <b>never</b> from caller-supplied headers.
    /// <c>null</c> for anonymous requests.
    /// </summary>
    public string? CallerName
    {
        get;
        init;
    }

    /// <summary>
    /// Roles of the authenticated caller, populated alongside
    /// <see cref="CallerName"/>. Empty for anonymous requests.
    /// </summary>
    public IReadOnlyCollection<string> CallerRoles
    {
        get;
        init;
    } = [];

    /// <summary>
    /// Returns <c>true</c> when the correlation context has no meaningful correlation fields set —
    /// indicating no correlation context has been established for the current request.
    /// </summary>
    public bool IsEmpty =>
        string.IsNullOrWhiteSpace(RequestId)
        && ProcessId is null
        && string.IsNullOrWhiteSpace(CallingProcessorName)
        && string.IsNullOrWhiteSpace(CallingStepName);
}
