namespace Kaleido.Observability;

[ExcludeFromCodeCoverage]
public sealed record KaleidoCorrelationContext
{
    /// <summary>
    /// The unique identifier of the originating request.
    /// Always non-empty — generated by the transport layer if not supplied by the caller.
    /// </summary>
    public string RequestId
    {
        get;
        init;
    } = string.Empty;

    public Guid? ProcessId
    {
        get;
        init;
    }

    public Guid? ProcessorInstanceId
    {
        get;
        init;
    }

    public string? SourceProcessorName
    {
        get;
        init;
    }

    /// <summary>
    /// The name of the process step making the current inter-service call, if propagated by the caller.
    /// Populated on queryable services when a process step calls them, enabling step-level traceability.
    /// </summary>
    public string? StepName
    {
        get;
        init;
    }

    /// <summary>
    /// Name of the authenticated caller, populated by the transport from the
    /// request principal — <b>never</b> from caller-supplied headers.
    /// <c>null</c> for anonymous requests.
    /// </summary>
    public string? CallerName
    {
        get;
        init;
    }

    /// <summary>
    /// Roles of the authenticated caller, populated alongside
    /// <see cref="CallerName"/>. Empty for anonymous requests.
    /// </summary>
    public IReadOnlyCollection<string> CallerRoles
    {
        get;
        init;
    } = [];

    /// <summary>
    /// Returns <c>true</c> when the correlation context has no meaningful correlation fields set —
    /// indicating no correlation context has been established for the current request.
    /// </summary>
    public bool IsEmpty =>
        string.IsNullOrWhiteSpace(RequestId)
        && ProcessId is null
        && ProcessorInstanceId is null
        && string.IsNullOrWhiteSpace(SourceProcessorName)
        && string.IsNullOrWhiteSpace(StepName);
}
