<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
		<Compile Include="..\Shared\AnalyzerTestHarness.cs" />
		<PackageReference Include="Basic.Reference.Assemblies" />
		<PackageReference Include="Basic.Reference.Assemblies.Net80" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\tools\analyzers\Kaleido.Analyzers.Testing\Kaleido.Analyzers.Testing.csproj" />
		<ProjectReference Include="..\..\src\Kaleido\Kaleido.csproj" />
	</ItemGroup>
</Project>
