<Project>
    <Import Project="$(MSBuildThisFileDirectory)..\Directory.Packages.props" />
    <ItemGroup>
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.31" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
        <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
        <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
        <PackageVersion Include="Yarp.ReverseProxy" Version="2.2.0" />
    </ItemGroup>
</Project>
