<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Kaleido.Http.Client\Kaleido.Http.Client.csproj" />
		<ProjectReference Include="..\..\src\Kaleido.Http.Abstractions\Kaleido.Http.Abstractions.csproj" />
		<ProjectReference Include="..\Kaleido.UnitTests\Kaleido.UnitTests.csproj" />
	</ItemGroup>
</Project>
