<Project Sdk="Microsoft.NET.Sdk.Web">
<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Kaleido.Http\Kaleido.Http.csproj" />
	  <ProjectReference Include="..\..\..\src\Kaleido.Observability.OpenTelemetry\Kaleido.Observability.OpenTelemetry.csproj" />
	  <ProjectReference Include="..\..\..\src\Kaleido.Provider.SQLite\Kaleido.Provider.SQLite.csproj" />
	  <ProjectReference Include="..\Process\Kaleido.Samples.ECommerce.Process.csproj" />
	  <ProjectReference Include="..\Queryable\Kaleido.Samples.ECommerce.Queryable.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="Kaleido.Queryable" />
		<Using Include="Kaleido.Queryable.Query" />
	</ItemGroup>
</Project>
