<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Kaleido.Process" />
		<Using Include="Kaleido.Process.Execution" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Kaleido\Kaleido.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Kaleido.Provider.SQLite.UnitTests" />
	</ItemGroup>

</Project>
