<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Kaleido\Kaleido.csproj" />
		<ProjectReference Include="..\..\src\Kaleido.Provider.SQLite\Kaleido.Provider.SQLite.csproj" />
	</ItemGroup>
</Project>
