name: Dependency review

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  review:
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Review dependencies
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        deny-licenses: AGPL-1.0-only, AGPL-1.0-or-later, AGPL-3.0-only, AGPL-3.0-or-later
